085_Entity > Parent: Create a new record
SamJulia/qa-for-everyone pull request #11
Opened 2021-06-06 07:15 UTC by gmirzoyan

https://trello.com/c/AocU1dNP

2021-06-06 21:49 UTC, Liana-Harutyunyan approved these changes
All tests passed

2021-06-07 05:37 UTC, SamJulia requested changes

2021-06-07 05:37 UTC, SamJulia commented on test/specs/example.js
> +        browser.url('https://ref2.eteam.work/');
don't need to add url here

2021-06-07 05:37 UTC, SamJulia commented on test/specs/example.js
> +});
very good 👌🏻 need to create a new page for this and try to have an assertion for each it

2021-06-07 07:24 UTC, gmirzoyan commented on test/specs/example.js
> +});
Thank you for review. I will make requested changes in the new PR.

2021-06-15 21:52 UTC, closed without merging