001 Board: Create a new record
SamJulia/qa-for-everyone pull request #12
Opened 2021-06-06 12:34 UTC by Nifargo

https://trello.com/c/fKdWIHGS

2021-06-06 13:32 UTC, Burdishka commented
Entity Board - Create new record: эта user story уже занята как я вижу. Даже есть уже [PR #6](https://github.com/SamJulia/qa-for-everyone/pull/6)

2021-06-06 13:35 UTC, Burdishka commented on test/specs/example.js
> +        expect(verific.getText()).to.equal('Board')
А как ты тут делаешь проверку? Просто проверяешь то что ты попадаешь на страничку с хедером Board?

2021-06-06 13:38 UTC, Burdishka commented
Ссылка на карточку в Trello у тебя есть в этом PR - отлично. Но в самой AT карточке в Trello нужно оставить линк на PR.

2021-06-06 13:47 UTC, Burdishka commented
example.js  - название файла надо бы изменить, и назвать соответственно к entity как-то

2021-06-07 05:31 UTC, SamJulia requested changes

2021-06-07 05:31 UTC, SamJulia commented on test/specs/example.js
> +});
very good 👌🏻 next time try to add expect to each it to check your steps

2021-06-07 05:32 UTC, closed without merging

2021-06-07 07:23 UTC, Nifargo commented on test/specs/example.js
> +        expect(verific.getText()).to.equal('Board')
ну если ты перешел на страницу с таблицами то значит все прошло успешно в ином случаи была б ошибка и юзер остался б на странице создания борда

2021-06-07 07:23 UTC, Nifargo commented on test/specs/example.js
> +});
okay ill do it. thx