023 Entity-Tag. Create new record and save.
SamJulia/qa-for-everyone pull request #19
Opened 2021-06-07 05:34 UTC by LMalushkina

Test create new record in Tag, https://trello.com/c/CZH0ItMe/434-at023javascript-entity-tag-create-a-new-record.

2021-06-07 05:40 UTC, SamJulia requested changes

2021-06-07 05:40 UTC, SamJulia commented on test/specs/entityTagNewRecord.js
> +        browser.url('https://ref2.eteam.work/');
do not need to add url here

2021-06-07 05:40 UTC, SamJulia commented on test/specs/entityTagNewRecord.js
> +        expect($(checkSqrSign).isExisting());
need to have a to.eq if you use expect, wdio can pass both true and false

2021-06-07 05:40 UTC, SamJulia commented on test/specs/entityTagNewRecord.js
> +        expect($(result).isDisplayed());
need to have a to.eq if you use expect, wdio can pass both true and false

2021-06-07 05:40 UTC, SamJulia commented on test/specs/entityTagNewRecord.js
> +});
very good 👌🏻, try to have a assertion in each it like a test case

2021-06-07 05:43 UTC, LMalushkina commented on test/specs/entityTagNewRecord.js
> +        browser.url('https://ref2.eteam.work/');
Ok, I will change that.

2021-06-07 05:45 UTC, LMalushkina commented on test/specs/entityTagNewRecord.js
> +        expect($(checkSqrSign).isExisting());
ok

2021-06-07 05:49 UTC, LMalushkina commented on test/specs/entityTagNewRecord.js
> +});
Thank you. I will try.

2021-06-07 07:03 UTC, SergeiKuznetsov commented
@LMalushkina виноват, нечаянно обновил ветку. Перед тем как добавлять у себя новые коммиты, сделайте **git pull**

2021-06-07 07:45 UTC, SergeiKuznetsov commented on test/specs/entityTagNewRecord.js
> +});
![image](https://user-images.githubusercontent.com/13728212/120976638-6198fc00-c727-11eb-838f-ac4912478176.png)
GitHub вот так ругается, когда вы забываете нажать Enter в конце последней строки кода.
В WebStorm будет казаться что появилась лишняя пустая строка в конце файла, но на самом деле это только так кажется. Сам этот newline важен для корректной работы Git.
Если интересно, я могу потом объяснить и показать, почему это важно.
В некоторых командах этот момент даже упоминают в Style Guide.

А вот в 80-ю строку наоборот стоит удалить. Там пустая строка лишняя.

2021-06-13 22:25 UTC, Burdishka commented
eventsChain1.js - Why is this file in PR?

2021-06-13 22:29 UTC, LMalushkina commented
Не знаю, может что-то не то нажала.

2021-06-13 22:31 UTC, LMalushkina commented
Три дня назад я делала только review этой entity

2021-06-13 22:38 UTC, Burdishka commented
> Три дня назад я делала только review этой entity

ты можешь создать новую ветку и сделать новый PR?
а то ты сейчас весь проект одним пул реквестом удалишь)))))

2021-06-13 22:39 UTC, LMalushkina commented
Хорошо, сейчас эту удалю и сделаю новую

2021-06-13 22:40 UTC, closed without merging