Andrw
SamJulia/qa-for-everyone pull request #38
Opened 2021-06-13 13:42 UTC by Nifargo

Selectors for the Footers

2021-06-13 14:43 UTC, dashasandler commented
Looks good, but strange name "Andrw" what does it mean?

2021-06-13 17:42 UTC, dashasandler approved these changes

2021-06-13 17:59 UTC, MariaMoroz commented
Change, please, the name of PR

2021-06-13 18:12 UTC, SergeiKuznetsov commented
The name of the PR will go into the header of the squash commit message, and you have a meaningless set of letters there.

2021-06-13 23:27 UTC, SamJulia commented on package.json
> +    "@wdio/sync": "^7.7.3",
you do not need to change package.json file

2021-06-14 18:25 UTC, SamJulia requested changes
Does't need to update package.js

2021-06-14 23:47 UTC, SergeiKuznetsov commented
you do not need to delete package.json file

2021-06-15 00:39 UTC, SergeiKuznetsov commented
@SamJulia tests are unstable. 
Is it because everyone runs under the same user?

2021-06-16 23:43 UTC, closed without merging