023 Entity-Tag, create new record/ https://trello.com/c/CZH0ItMe/434-at023
SamJulia/qa-for-everyone pull request #4
Opened 2021-06-02 20:37 UTC by LMalushkina

Test create new record in Tag, https://trello.com/c/CZH0ItMe/434-at023javascript-entity-tag-create-a-new-record

2021-06-02 23:32 UTC, MariaMoroz requested changes
При запуске теста, все зависает из-за локатора 04/LP - //div[@class='sidebar-wrapper']
У Вас тест проходит успешно?
Когда я меня Ваш локатор на другой(//div[@class='sidebar']), тест запускается, но опять не проходит, выводит ошибки в 07/LP-Should choose user" и 08/LP-Should save new record: 
ERROR webdriver: Request failed with status 400 due to element not interactable: element not interactable

2021-06-02 23:35 UTC, MariaMoroz commented
ссылку на карточку в трелло надо убрать из названия PR

2021-06-02 23:42 UTC, LMalushkina commented
> При запуске теста, все зависает из-за локатора 04/LP - //div[@Class='sidebar-wrapper']
> У Вас тест проходит успешно?
> Когда я меня Ваш локатор на другой(//div[@Class='sidebar']), тест запускается, но опять не проходит, выводит ошибки в 07/LP-Should choose user" и 08/LP-Should save new record:
> ERROR webdriver: Request failed with status 400 due to element not interactable: element not interactable

2021-06-02 23:43 UTC, LMalushkina commented
у меня тест проходит,  сейчас проверила

<img width="1104" alt="Screen Shot 2021-06-02 at 4 40 02 PM" src="https://user-images.githubusercontent.com/65260023/120565305-9c1a3600-c3c1-11eb-8f48-1151e16d14fd.png">

2021-06-02 23:51 UTC, MariaMoroz commented
> 
> 
> у меня тест проходит, сейчас проверила
> 
> <img alt="Screen Shot 2021-06-02 at 4 40 02 PM" width="1104" src="https://user-images.githubusercontent.com/65260023/120565305-9c1a3600-c3c1-11eb-8f48-1151e16d14fd.png">

Интересный случай :) 
если я запускаю ничего не меняя в Вашем коде, тогда глазами я вижу только как отрылся сайт, залогинился пользователь и больше ничего не происходит на сайте, а в вебшторме выходят  вот такие ошибки:
![image](https://user-images.githubusercontent.com/82988399/120565845-ef997d80-c3db-11eb-8078-e98d0ceeadd4.png)

2021-06-02 23:52 UTC, MariaMoroz commented
если меняю локатор, то все поэтапно вижу на сайте и выходят только две ошибки ,как я писала выше

2021-06-02 23:57 UTC, LMalushkina commented
А может быть так, что у меня компьютер быстрее работает/скорость исполнения выше, я все ожидания/pause удалила, потому что с ними у меня очень медленно открывался сайт, тест очень медленно исполнялся. Нужно чтоб ещё кто-нибудь проверил.

2021-06-03 06:21 UTC, TupakAmaru13 requested changes
У меня проходят первые 4 теста только

2021-06-03 06:57 UTC, LMalushkina commented
Мы вечером выходили в Zoom с Maria, и у неё мои тесты также не проходили, а у меня все отлично проходит. Все wait я убрала у меня без них все тесты проходят. И ещё одна удивительная вещь у меня работаю оба локатора в тесте 05/LP (был до изменения 04/LP, я добавила тест reset) //div[@class=‘sidebar-wrapper’] и //div[@class=‘sidebar’] и оба локатора у меня есть, а у Maria нет локатора -//div[@class=‘sidebar-wrapper’], мы это проверили и у меня и у неё. Вообщем непонятно.

2021-06-03 06:58 UTC, LMalushkina commented
<img width="1104" alt="Screen Shot 2021-06-02 at 11 57 34 PM" src="https://user-images.githubusercontent.com/65260023/120601123-69426300-c3fe-11eb-9174-dac7fac2be9e.png">

2021-06-03 07:00 UTC, LMalushkina commented
Тест сейчас запустила, у меня все работает, I am confused

2021-06-03 13:56 UTC, Burdishka commented on test/specs/entityTagCreateNewRecord.js
> +// import selectors from './../../data/selectors.json'
забыли убрать комментарии

2021-06-03 13:56 UTC, Burdishka commented on test/specs/entityTagCreateNewRecord.js
> +    it('03/LP-Should verify login name IF accept valid data', () => {
у вас название тестов продублировано

2021-06-03 16:04 UTC, LMalushkina commented on test/specs/entityTagCreateNewRecord.js
> +    it('03/LP-Should verify login name IF accept valid data', () => {
Спасибо, переделаю

2021-06-03 16:05 UTC, LMalushkina commented on test/specs/entityTagCreateNewRecord.js
> +// import selectors from './../../data/selectors.json'
ok, переделаю

2021-06-03 17:10 UTC, LMalushkina commented on test/specs/entityTagCreateNewRecord.js
> +// import selectors from './../../data/selectors.json'
Done

2021-06-03 17:10 UTC, LMalushkina commented on test/specs/entityTagCreateNewRecord.js
> +    it('03/LP-Should verify login name IF accept valid data', () => {
Done

2021-06-07 05:02 UTC, closed without merging