AT_019.01_JavaScript | Entity > Calendar: Delete record with corrected Xpaths
SamJulia/qa-for-everyone pull request #8
Opened 2021-06-05 14:38 UTC by dashasandler

2021-06-05 20:06 UTC, MariaMoroz approved these changes
LGTM

2021-06-05 20:42 UTC, gmirzoyan approved these changes
Good job! All tests were passed.

2021-06-05 22:15 UTC, TupakAmaru13 approved these changes

2021-06-05 22:16 UTC, TupakAmaru13 commented
Good job!

2021-06-07 05:27 UTC, SamJulia requested changes

2021-06-07 05:27 UTC, SamJulia commented on test/specs/CalendarDelrecord.js
> +    });
very good 👌🏻 next time try to add assertion to check you steps to each it.

2021-06-07 05:33 UTC, closed without merging